### ISSUE TITLE
terraform-provider-akamai download

### ISSUE THREAD

**Issue by FLGale** [terraform-providers/terraform-provider-akamai#4]
Hi there,

Are we able to download this provider like standard terraform providers or do we need to follow the inaccurate instructions on the [readme](https://github.com/terraform-providers/terraform-provider-akamai#building-the-provider) page stating to 'git clone' from the old akamai repo?

```
terraform-11-13 version
Terraform v0.11.13

terraform-11-13 init -upgrade
Upgrading modules...
- module.akamai-test
  Updating source "../modules/akamai/property"
- module.akamai-test-2
  Updating source "../modules/akamai/property"
- module.akamai-test-3
  Updating source "../modules/akamai/property"
- module.akamai-test-4
  Updating source "../modules/akamai/property"

Initializing the backend...

Initializing provider plugins...
failed to read provider plugin /root/go/bin/terraform-provider-akamai: open /root/go/bin/terraform-provider-akamai: no such file or directory
```

Also, any updates as to when the 'is_secure' feature will work?

**Comment by dshafik** [comment]
@FLGale If you are using Terraform 0.12, the provider should be automatically installed with `terraform init`.

As for secure properties, we now have support for using Standard TLS and Enhanced TLS hostnames, which can (or must) be associated with a certificate.

Let me know if this helps.

**Comment by FLGale** [comment]
Following up for others that might have installed from source and now can't get it to download the new version.  I had problems doing this after migrating to TF 0.12 and found this case I started.

I found the following in the notes I made.  I commented out the config below and was able to download the newest version.

### Install from source

If you'd prefer to install from source:

1. Add `terraform-provider-akamai` to your `~/.terraformrc` file:

```
providers {
  "akamai" = "$GOPATH/bin/terraform-provider-akamai"
}
```

Kill the above with fire to make it work like other TF Providers.
